export const ACTIVATE_CONFIGURE_WINDOW: "sanascan/ACTIVATE_CONFIGURE_WINDOW"
  = "sanascan/ACTIVATE_CONFIGURE_WINDOW";

export const DEACTIVATE_CONFIGURE_WINDOW: "sanascan/DEACTIVATE_CONFIGURE_WINDOW"
  = "sanascan/DEACTIVATE_CONFIGURE_WINDOW";
