export const ACTIVATE_CONFIGURE: "sanascan/ACTIVATE_CONFIGURE"
  = "sanascan/ACTIVATE_CONFIGURE";

export const DEACTIVATE_CONFIGURE: "sanascan/DEACTIVATE_CONFIGURE"
  = "sanascan/DEACTIVATE_CONFIGURE";
